# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: IMS New Reserchers Group
email: ims@imstat.org
description: > # this means to ignore newlines until "baseurl:"
  The IMS New Researchers Group works to foster new researchers in statistics by hosting
  a conference every year before JSM and maintaining this website with useful resources.
baseurl: "/imsnrg" # the subpath of your site, e.g. /blog
url:  # the base hostname & protocol for your site

# Build settings
markdown: kramdown
